### ISSUE TITLE
Separate SCSS file imports

### ISSUE THREAD

**Issue by Jared-Dev** [zeniagist/midwestern-technical-challenge#2]
Can the `_app.jsx` be updated to only import bootstrap and the global SCSS?

Doing so the navbar would import the SCSS it needs. Then the two pages would do the same.

[Here](https://nextjs.org/docs/basic-features/built-in-css-support#sass-support) are the relevant docs!

**Comment by zeniagist** [comment]
Removed all scss files but global and imported module.scss files in respective pages and components.

Branch: SCCS-import
