### ISSUE TITLE
Make the layout more "DRY"

### ISSUE THREAD

**Issue by Jared-Dev** [zeniagist/midwestern-technical-challenge#3]
Can you. move the `Navbar` inside of a `Layout` component and encapsulate the `pathName` logic in the layout.

Once this is done the outer `<Fragment>` (`<>`) won't be necessary and should allow the removal of the repeated code for getting the path!

**Comment by zeniagist** [comment]
- Moved navbar inside SimpleLayout component and passed pathName props to Navbar. 
- Encapsulated pathName logic in layout and passed props in home (index) and contact
- removed outer fragments

Branch: navbar-layout
